# Generated by Django 2.1.5 on 2019-02-06 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerInteger',
            fields=[
                ('surveyquestion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='survey.SurveyQuestion')),
                ('body', models.IntegerField(blank=True, null=True)),
            ],
            bases=('survey.surveyquestion',),
        ),
        migrations.CreateModel(
            name='AnswerRadio',
            fields=[
                ('surveyquestion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='survey.SurveyQuestion')),
                ('body', models.TextField(blank=True, null=True)),
            ],
            bases=('survey.surveyquestion',),
        ),
        migrations.CreateModel(
            name='AnswerSelect',
            fields=[
                ('surveyquestion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='survey.SurveyQuestion')),
                ('body', models.TextField(blank=True, null=True)),
            ],
            bases=('survey.surveyquestion',),
        ),
        migrations.CreateModel(
            name='AnswerSelectMultiple',
            fields=[
                ('surveyquestion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='survey.SurveyQuestion')),
                ('body', models.TextField(blank=True, null=True)),
            ],
            bases=('survey.surveyquestion',),
        ),
        migrations.CreateModel(
            name='AnswerText',
            fields=[
                ('surveyquestion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='survey.SurveyQuestion')),
                ('body', models.TextField(blank=True, null=True)),
            ],
            bases=('survey.surveyquestion',),
        ),
    ]
