# Generated by Django 2.1.5 on 2019-02-07 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_answerinteger_answerradio_answerselect_answerselectmultiple_answertext'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField(blank=True, null=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Employee')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Question')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Survey')),
            ],
        ),
        migrations.RemoveField(
            model_name='answerinteger',
            name='surveyquestion_ptr',
        ),
        migrations.RemoveField(
            model_name='answerradio',
            name='surveyquestion_ptr',
        ),
        migrations.RemoveField(
            model_name='answerselect',
            name='surveyquestion_ptr',
        ),
        migrations.RemoveField(
            model_name='answerselectmultiple',
            name='surveyquestion_ptr',
        ),
        migrations.RemoveField(
            model_name='answertext',
            name='surveyquestion_ptr',
        ),
        migrations.DeleteModel(
            name='AnswerInteger',
        ),
        migrations.DeleteModel(
            name='AnswerRadio',
        ),
        migrations.DeleteModel(
            name='AnswerSelect',
        ),
        migrations.DeleteModel(
            name='AnswerSelectMultiple',
        ),
        migrations.DeleteModel(
            name='AnswerText',
        ),
    ]
