# Generated by Django 2.1.7 on 2019-02-27 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_auto_20190227_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='company',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
