# Generated by Django 2.1.7 on 2019-02-27 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_auto_20190227_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyquestion',
            name='date',
        ),
    ]
