# Generated by Django 2.1.7 on 2019-02-27 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0007_remove_surveyquestion_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='user',
        ),
    ]
